Feature: Add Club scenarios

  Background: Login as lead
    Given User open the main page of the site and login as lead

  Scenario Outline: Verify that lead as a correct input can enter 40, 1000 and 1500 of valid symbols to description field when creating new club
    When User opens add club main info component
    Then User enters "TestClub" into club 'Назва' field
    And User chooses club category 4
    And User enters child minimum age "3"
    And User enters child maximum age "16"
    Then User clicks the 'Next' button and navigates further to Contacts component
    And User enters phone number "0987776655"
    Then User clicks the 'Next' button and navigates further to Description component
    And User enters "<description>" to 'Опис' field
    Then Description field validation success


    Examples:

      | description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
      | 1234567890123456789012345678901234567890                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | !&quot;#$%&amp;()*+,-./:;&lt;=&gt;?@[]^_`~}/!#$%&amp;'(^)*+,-./:;&lt;=&gt;?@[]^_`{~+                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
      | At vero eos et accusamus et iusto odio..                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | Діти з 3 років розвивають креативність..                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id este laborum et dolorum fuga.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | Верховна Рада України від імені Українського народу - громадян України всіх національностей, виражаючи суверенну волю народу, спираючись на багатовікову історію українського державотворення і на основі здійсненого українською нацією, усім Українським народом права на самовизначення, дбаючи про забезпечення прав і свобод людини та гідних умов її життя, піклуючись про зміцнення громадянської злагоди на землі України та підтверджуючи європейську ідентичність Українського народу і незворотність європейського та євроатлантичного курсу України, прагнучі розвивати і зміцнювати демократичну, соціальну, правову державу, усвідомлюючи відповідальність перед Богом, власною совістю, попередніми, нинішнім та прийдешніми поколіннями, керуючись Актом проголошення незалежності України від 24 серпня 1991 року, схваленим 1 грудня 1991 року всенародним голосуванням, приймає цю Конституцію - Основний Закон України. Суверенітет України поширюється на всю її територію. Ніхто не може узурпувати державну владу                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere p. |
      | Верховна Рада України від імені Українського народу - громадян України всіх національностей, виражаючи суверенну волю народу, спираючись на багатовікову історію українського державотворення і на основі здійсненого українською нацією, усім Українським народом права на самовизначення, дбаючи про забезпечення прав і свобод людини та гідних умов її життя, піклуючись про зміцнення громадянської злагоди на землі України та підтверджуючи європейську ідентичність Українського народу і незворотність європейського та євроатлантичного курсу України, прагнучі розвивати і зміцнювати демократичну, соціальну, правову державу, усвідомлюючи відповідальність перед Богом, власною совістю, попередніми, нинішнім та прийдешніми поколіннями, керуючись Актом проголошення незалежності України від 24 серпня 1991 року, схваленим 1 грудня 1991 року всенародним голосуванням, приймає цю Конституцію - Основний Закон України. Суверенітет України поширюється на всю її територію. Ніхто не може узурпувати державну владу. Україна є республікою. Носієм суверенітету і єдиним джерелом влади в Україні є народ. Народ здійснює владу безпосередньо і через органи державної влади та органи місцевого самоврядування. Право визначати і змінювати конституційний лад в Україні належить виключно народові і не може бути узурповане державою, її органами або посадовими особами. В Україні існує єдине громадянство. Підстави набуття і припинення громадянства визначаються законом, та визнається і гарантується місцеве самоврядування.. |


  Scenario Outline: Verify that lead gets 'Опис гуртка може містити від 40 до 1500 символів' error message when enters less than 40 symbols into the description field
    Then User opens add club main info component
    Then User enters "TestClub" into club 'Назва' field
    And User chooses club category 4
    And User enters child minimum age "3"
    And User enters child maximum age "16"
    Then User clicks the 'Next' button and navigates further to Contacts component
    And User enters phone number "0987776655"
    Then User clicks the 'Next' button and navigates further to Description component
    And User enters "<description>" to 'Опис' field
    Then Error message "<expectedErrorMsg>" appeared


    Examples:

      | description                             | expectedErrorMsg                                  |
      | A                                       | Опис гуртка може містити від 40 до 1500 символів. |
      | At vero eos et accus                    | Опис гуртка може містити від 40 до 1500 символів. |
      | At vero eos et accusamus et iusto odio. | Опис гуртка може містити від 40 до 1500 символів. |